[default.databases.postgres_db]
pool_size = 40

[default]
cors_origins = ["http://localhost:5501"]
cors_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
cors_headers = ["Authorization", "Content-Type"]